version: '3.8'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: task-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Panos993##
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db-data:
