services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: task-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Panos993##
      POSTGRES_PORT: 5433
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "54321:5433"
    networks:
      - app-network
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Panos993##
      DB_NAME: task-db
      JWT_SECRET: Panos1212@!@!
      NODE_ENV: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: development
    networks:
      - app-network
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge
    
volumes:
  db-data: